[package]
name = "mozy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mozy"
crate-type = ["cdylib"]

[dependencies]
binread = "2.2.0"
midly = "0.5.3"
pyo3 = "0.20.0"
